"""
Django settings for tg_bot_admin project.

Generated by 'django-admin startproject' using Django 3.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1^n9+p-fmk__+oywm$zva)6jxp#1*8hgz4msiu7r0k@7&u)ja4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'thoughtfully-active-manakin.cloudpub.ru',
    '.cloudpub.ru',  # Разрешаем все поддомены cloudpub.ru
    '188.215.229.165',
    'webnet.panel-fran-patriot.com.de',
    '.panel-fran-patriot.com.de',  # Разрешаем все поддомены
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'bot_management',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tg_bot_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tg_bot_admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'tg_key_bot.db',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # Только для разработки!
CORS_ALLOW_CREDENTIALS = True

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# Настройки для интеграции с ботом
BOT_TOKEN = 'your_bot_token_here'  # Будет переопределено из config.py
ADMIN_IDS = []  # Будет переопределено из config.py

# Настройки ЮKassa
YOOKASSA_SHOP_ID = '1164974'  # Будет переопределено из config.py
YOOKASSA_SECRET_KEY = 'test_9tNtDsJFy4h-_hGjtuUCrH0Tw3bwvQWAFdx4BgdkPHc'  # Будет переопределено из config.py
YOOKASSA_WEBHOOK_URL = 'http://127.0.0.1:8123/bot_management/webhook/yookassa/'  # Будет переопределено из config.py

# Login/Logout redirect URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/bot_management/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Импортируем настройки из config.py если возможно
try:
    from config import (
        BOT_TOKEN as CONFIG_BOT_TOKEN,
        ADMIN_IDS as CONFIG_ADMIN_IDS,
        YOOKASSA_SHOP_ID as CONFIG_YOOKASSA_SHOP_ID,
        YOOKASSA_SECRET_KEY as CONFIG_YOOKASSA_SECRET_KEY,
        YOOKASSA_WEBHOOK_URL as CONFIG_YOOKASSA_WEBHOOK_URL,
        REMNAWAVE_BASE_URL as CONFIG_REMNAWAVE_BASE_URL,
        REMNAWAVE_API_KEY as CONFIG_REMNAWAVE_API_KEY,
        REMNAWAVE_DEFAULT_SQUAD_UUID as CONFIG_REMNAWAVE_DEFAULT_SQUAD_UUID,
        REMNAWAVE_BYPASS_BASE_URL as CONFIG_REMNAWAVE_BYPASS_BASE_URL,
        REMNAWAVE_BYPASS_API_KEY as CONFIG_REMNAWAVE_BYPASS_API_KEY,
        REMNAWAVE_BYPASS_DEFAULT_SQUAD_UUID as CONFIG_REMNAWAVE_BYPASS_DEFAULT_SQUAD_UUID,
        REMNAWAVE_FAST_VPN_SQUAD_UUID as CONFIG_REMNAWAVE_FAST_VPN_SQUAD_UUID,
    )
    BOT_TOKEN = CONFIG_BOT_TOKEN
    ADMIN_IDS = CONFIG_ADMIN_IDS
    YOOKASSA_SHOP_ID = CONFIG_YOOKASSA_SHOP_ID
    YOOKASSA_SECRET_KEY = CONFIG_YOOKASSA_SECRET_KEY
    YOOKASSA_WEBHOOK_URL = CONFIG_YOOKASSA_WEBHOOK_URL
    # Remnawave API настройки (Обычный VPN)
    REMNAWAVE_BASE_URL = CONFIG_REMNAWAVE_BASE_URL
    REMNAWAVE_API_KEY = CONFIG_REMNAWAVE_API_KEY
    REMNAWAVE_DEFAULT_SQUAD_UUID = CONFIG_REMNAWAVE_DEFAULT_SQUAD_UUID
    # Remnawave Bypass API настройки (ОБХОД глушилок + VPN)
    REMNAWAVE_BYPASS_BASE_URL = CONFIG_REMNAWAVE_BYPASS_BASE_URL
    REMNAWAVE_BYPASS_API_KEY = CONFIG_REMNAWAVE_BYPASS_API_KEY
    REMNAWAVE_BYPASS_DEFAULT_SQUAD_UUID = CONFIG_REMNAWAVE_BYPASS_DEFAULT_SQUAD_UUID
    REMNAWAVE_FAST_VPN_SQUAD_UUID = CONFIG_REMNAWAVE_FAST_VPN_SQUAD_UUID
except ImportError:
    pass

# Настройки безопасности (только для бота)
X_FRAME_OPTIONS = 'DENY'

# Логирование безопасности бота
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'bot_security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'bot_security.log',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'bot_management.bot_security': {
            'handlers': ['bot_security_file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}
