events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    upstream bot_backend {
        server telegram-vpn-bot:8123;
    }

    server {
        listen 80;
        server_name webnet.panel-fran-patriot.com.de;

        location /webhook {
            proxy_pass http://bot_backend/bot_management/webhook/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Apay-Callback $http_x_apay_callback;
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }

        location / {
            proxy_pass http://bot_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /health {
            proxy_pass http://bot_backend/bot_management/api/health/;
        }

        listen 443 ssl;
        ssl_certificate /etc/letsencrypt/live/webnet.panel-fran-patriot.com.de/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/webnet.panel-fran-patriot.com.de/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        # Убираем ssl_dhparam
        # ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    }

    server {
        if ($host = webnet.panel-fran-patriot.com.de) {
            return 301 https://$host$request_uri;
        }
        listen 80;
        server_name webnet.panel-fran-patriot.com.de;
        return 404;
    }
}