# Generated by Django 5.2.7 on 2025-10-14 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('admin_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('last4', models.CharField(max_length=4)),
                ('bank_name', models.CharField(max_length=100)),
                ('max_limit', models.IntegerField()),
                ('current_received', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionKey',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_value', models.CharField(max_length=255, unique=True)),
                ('subscription_type', models.CharField(choices=[('month', 'Месячная'), ('forever', 'Пожизненная')], max_length=10)),
                ('total_activations', models.IntegerField(choices=[(1, '1 активация'), (3, '3 активации'), (4, '4 активации')])),
                ('used_activations', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ключ подписки',
                'verbose_name_plural': 'Ключи подписок',
                'db_table': 'keys',
            },
        ),
        migrations.CreateModel(
            name='SupportChat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Чат поддержки',
                'verbose_name_plural': 'Чаты поддержки',
                'db_table': 'support_chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('broadcast_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('sent_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='bot_management.adminuser')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], max_length=10)),
                ('text', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot_management.supportchat')),
            ],
            options={
                'verbose_name': 'Сообщение поддержки',
                'verbose_name_plural': 'Сообщения поддержки',
                'db_table': 'support_messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.AddField(
            model_name='supportchat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chats', to='bot_management.telegramuser'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('pdf_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('has_receipt', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтвержден'), ('rejected', 'Отклонен')], default='pending', max_length=10)),
                ('subscription_type', models.CharField(choices=[('month', 'Месячная'), ('forever', 'Пожизненная')], max_length=10)),
                ('issued_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_management.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bot_management.telegramuser')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
