# Generated by Django 5.2.7 on 2025-10-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='confirmed_at',
            new_name='paid_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='has_receipt',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pdf_file_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='yookassa_confirmation_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачен'), ('canceled', 'Отменен'), ('failed', 'Ошибка оплаты')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
