# Generated by Django 5.2.7 on 2025-10-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0002_remove_payment_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportchat',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supportchat',
            name='unread_admin_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supportchat',
            name='unread_user_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
