# Generated by Django 5.2.7 on 2025-10-14 21:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0003_supportchat_ticket_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная сумма')], max_length=10, verbose_name='Тип скидки')),
                ('discount_value', models.IntegerField(verbose_name='Размер скидки')),
                ('min_amount', models.IntegerField(default=0, verbose_name='Минимальная сумма заказа')),
                ('max_uses', models.IntegerField(blank=True, null=True, verbose_name='Максимум использований')),
                ('used_count', models.IntegerField(default=0, verbose_name='Количество использований')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('expired', 'Истек')], default='active', max_length=10, verbose_name='Статус')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'db_table': 'promo_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to='bot_management.telegramuser')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='bot_management.telegramuser')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
                'db_table': 'referrals',
                'unique_together': {('referrer', 'referred')},
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Реферальный код')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to='bot_management.telegramuser')),
            ],
            options={
                'verbose_name': 'Реферальный код',
                'verbose_name_plural': 'Реферальные коды',
                'db_table': 'referral_codes',
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('percent', 'Процент от покупки'), ('fixed', 'Фиксированная сумма'), ('key', 'Бесплатный ключ')], max_length=10, verbose_name='Тип награды')),
                ('reward_value', models.IntegerField(verbose_name='Размер награды')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Выплачено'), ('cancelled', 'Отменено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Выплачено')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='bot_management.referral')),
            ],
            options={
                'verbose_name': 'Награда за реферала',
                'verbose_name_plural': 'Награды за рефералов',
                'db_table': 'referral_rewards',
            },
        ),
        migrations.CreateModel(
            name='PromoUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.IntegerField(verbose_name='Размер скидки')),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Использован')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usage', to='bot_management.payment')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='bot_management.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to='bot_management.telegramuser')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
                'db_table': 'promo_usages',
                'unique_together': {('promo_code', 'user', 'payment')},
            },
        ),
    ]
