# Generated by Django 5.2.7 on 2025-10-14 22:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0007_auto_20251015_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Списание'), ('purchase', 'Покупка'), ('refund', 'Возврат'), ('referral', 'Реферальная награда')], max_length=20, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_transactions', to='bot_management.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to='bot_management.telegramuser')),
            ],
            options={
                'verbose_name': 'Транзакция баланса',
                'verbose_name_plural': 'Транзакции баланса',
                'db_table': 'balance_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
