# Generated by Django 5.2.7 on 2025-10-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0008_telegramuser_balance_balancetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='photo_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID фото'),
        ),
    ]
