# Generated by Django 5.2.7 on 2025-10-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0009_supportmessage_photo_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='first_entry_method',
            field=models.CharField(blank=True, choices=[('direct', 'Прямой вход (без реферальной ссылки)'), ('referral', 'По реферальной ссылке')], max_length=20, null=True, verbose_name='Способ первого входа'),
        ),
    ]
