# Generated by Django 5.2.7 on 2025-10-18 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0011_botsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='referral_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Реферальный баланс'),
        ),
        migrations.CreateModel(
            name='ReferralWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма к выводу')),
                ('payment_method', models.CharField(choices=[('bank_card', 'Банковская карта'), ('qiwi', 'QIWI'), ('yoomoney', 'ЮMoney'), ('sberbank', 'Сбербанк'), ('tinkoff', 'Тинькофф')], max_length=20, verbose_name='Способ выплаты')),
                ('payment_details', models.TextField(verbose_name='Реквизиты для выплаты')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('completed', 'Выплачено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий администратора')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_withdrawals', to='bot_management.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на вывод реферальных средств',
                'verbose_name_plural': 'Запросы на вывод реферальных средств',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('referral_reward', 'Реферальная награда'), ('withdrawal_request', 'Запрос на вывод'), ('withdrawal_completed', 'Вывод завершен'), ('withdrawal_cancelled', 'Вывод отменен')], max_length=30, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_balance_transactions', to='bot_management.telegramuser')),
                ('withdrawal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='bot_management.referralwithdrawal')),
            ],
            options={
                'verbose_name': 'Транзакция реферального баланса',
                'verbose_name_plural': 'Транзакции реферального баланса',
                'ordering': ['-created_at'],
            },
        ),
    ]
