# Generated by Django 5.2.7 on 2025-10-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0012_telegramuser_referral_balance_referralwithdrawal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralwithdrawal',
            name='payment_method',
            field=models.CharField(choices=[('bank_card', 'Банковская карта'), ('yoomoney', 'ЮMoney'), ('sberbank', 'Сбербанк'), ('tinkoff', 'Тинькофф')], max_length=20, verbose_name='Способ выплаты'),
        ),
    ]
