# Generated by Django 5.2.7 on 2025-10-19 12:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0013_alter_referralwithdrawal_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='multi_level_referral_enabled',
            field=models.BooleanField(default=False, verbose_name='Включена многоуровневая реферальная система'),
        ),
        migrations.CreateModel(
            name='MultiLevelReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='Уровень в цепочке')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент награды')),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма награды')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Выплачено'), ('canceled', 'Отменено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('original_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_level_rewards', to='bot_management.payment', verbose_name='Оригинальный платеж')),
                ('reward_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_level_rewards_received', to='bot_management.telegramuser', verbose_name='Получатель награды')),
            ],
            options={
                'verbose_name': 'Многоуровневая реферальная награда',
                'verbose_name_plural': 'Многоуровневые реферальные награды',
                'ordering': ['-created_at'],
                'unique_together': {('original_payment', 'reward_recipient', 'level')},
            },
        ),
    ]
