# Generated by Django 5.2.7 on 2025-10-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0014_telegramuser_multi_level_referral_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription_type',
            field=models.CharField(choices=[('month', 'Месячная'), ('year', 'Годовая')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionkey',
            name='subscription_type',
            field=models.CharField(choices=[('month', 'Месячная'), ('year', 'Годовая')], max_length=10),
        ),
        migrations.DeleteModel(
            name='MultiLevelReferralReward',
        ),
    ]
