# Generated by Django 6.0 on 2025-12-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0015_update_subscription_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionkey',
            name='total_activations',
            field=models.IntegerField(choices=[(1, '1 активация')]),
        ),
    ]
