# Generated by Django 6.0 on 2025-12-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0016_alter_subscriptionkey_total_activations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription_type',
            field=models.CharField(choices=[('month', 'Месячная'), ('3months', '3 месяца'), ('year', 'Годовая')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionkey',
            name='subscription_type',
            field=models.CharField(choices=[('month', 'Месячная'), ('3months', '3 месяца'), ('year', 'Годовая')], max_length=10),
        ),
    ]
