# Generated by Django 6.0 on 2025-12-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0017_alter_payment_subscription_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='platega_payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='platega_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
