# Generated by Django 6.0 on 2025-12-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0018_payment_platega_payment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionkey',
            name='total_activations',
            field=models.IntegerField(choices=[(1, '1 активация'), (2, '2 активации'), (3, '3 активации'), (4, '4 активации'), (5, '5 активаций')]),
        ),
    ]
