# Generated by Django 6.0 on 2025-12-18 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0019_alter_subscriptionkey_total_activations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Списание'), ('purchase', 'Покупка'), ('refund', 'Возврат'), ('referral', 'Реферальная награда')], db_index=True, max_length=20, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='issued_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачен'), ('canceled', 'Отменен'), ('failed', 'Ошибка оплаты')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription_type',
            field=models.CharField(choices=[('month', 'Месячная'), ('3months', '3 месяца'), ('year', 'Годовая')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Реферальный код'),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='referralreward',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='referralreward',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Выплачено'), ('canceled', 'Отменено')], db_index=True, default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='subscriptionkey',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionkey',
            name='key_value',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionkey',
            name='subscription_type',
            field=models.CharField(choices=[('month', 'Месячная'), ('3months', '3 месяца'), ('year', 'Годовая')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='supportchat',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supportchat',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], db_index=True, default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='supportchat',
            name='ticket_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sent_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_entry_method',
            field=models.CharField(blank=True, choices=[('direct', 'Прямой вход (без реферальной ссылки)'), ('referral', 'По реферальной ссылке')], db_index=True, max_length=20, null=True, verbose_name='Способ первого входа'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['user', 'status'], name='balance_tra_user_id_e37c08_idx'),
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['created_at'], name='balance_tra_created_240890_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_user_id_1b771c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_status_426d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['platega_transaction_id'], name='payments_platega_e9d390_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'is_active'], name='bot_managem_referre_266b24_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred'], name='bot_managem_referre_0736f7_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['is_active', 'created_at'], name='bot_managem_is_acti_0d2555_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code'], name='bot_managem_code_072e09_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['is_active'], name='bot_managem_is_acti_b516c2_idx'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['referral'], name='bot_managem_referra_520e69_idx'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['payment'], name='bot_managem_payment_0d18f1_idx'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['status', 'created_at'], name='bot_managem_status_8012b8_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionkey',
            index=models.Index(fields=['subscription_type', 'is_active'], name='keys_subscri_f839e9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionkey',
            index=models.Index(fields=['is_active', 'used_activations'], name='keys_is_acti_5d79aa_idx'),
        ),
        migrations.AddIndex(
            model_name='supportchat',
            index=models.Index(fields=['user', 'status'], name='support_cha_user_id_b64240_idx'),
        ),
        migrations.AddIndex(
            model_name='supportchat',
            index=models.Index(fields=['status', 'created_at'], name='support_cha_status_e21601_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['chat', 'sent_at'], name='support_mes_chat_id_b34732_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['chat', 'is_read'], name='support_mes_chat_id_842dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
    ]
