# Generated by Django 6.0 on 2026-01-06 12:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0020_alter_balancetransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата окончания подписки'),
        ),
        migrations.CreateModel(
            name='SubscriptionReminder',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('2_days_before', 'За 2 дня до окончания'), ('expired', 'Подписка истекла')], db_index=True, max_length=20)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='bot_management.payment')),
            ],
            options={
                'verbose_name': 'Напоминание о подписке',
                'verbose_name_plural': 'Напоминания о подписках',
                'db_table': 'subscription_reminders',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['payment', 'reminder_type'], name='subscriptio_payment_53f69f_idx'), models.Index(fields=['sent_at'], name='subscriptio_sent_at_b1f4ed_idx')],
                'unique_together': {('payment', 'reminder_type')},
            },
        ),
    ]
