# Generated by Django 6.0 on 2026-01-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0021_add_subscription_reminders'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionreminder',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='subscriptionreminder',
            name='subscriptio_payment_53f69f_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscriptionreminder',
            name='subscriptio_sent_at_b1f4ed_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subscription_expires_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='reminder_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Было ли отправлено напоминание о просроченном платеже'),
        ),
        migrations.DeleteModel(
            name='SubscriptionReminder',
        ),
    ]
