# Generated by Django 6.0 on 2026-01-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0022_alter_subscriptionreminder_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reminder_sent',
        ),
    ]
