# Generated by Django 6.0 on 2026-01-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0023_remove_payment_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата окончания подписки'),
        ),
    ]
