# Generated by Django 6.0 on 2026-01-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0024_add_subscription_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expiry_reminder_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Было ли отправлено уведомление о просроченной подписке'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reminder_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Было ли отправлено напоминание о незавершенном платеже'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription_reminder_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Было ли отправлено напоминание о заканчивающейся подписке'),
        ),
    ]
