# Generated by Django 6.0 on 2026-01-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0025_add_subscription_reminder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='trial_reminder_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Было ли отправлено уведомление об окончании пробного периода'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='trial_key_used',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Использован пробный ключ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Пробная (1 день)'), ('month', 'Месячная'), ('3months', '3 месяца'), ('year', 'Годовая')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionkey',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Пробная (1 день)'), ('month', 'Месячная'), ('3months', '3 месяца'), ('year', 'Годовая')], db_index=True, max_length=10),
        ),
    ]
