# Generated by Django 6.0 on 2026-01-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0026_payment_trial_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionkey',
            name='total_activations',
            field=models.IntegerField(choices=[(1, '1 активация'), (2, '2 активации'), (3, '3 активации'), (4, '4 активации'), (5, '5 активаций'), (6, '6 активаций'), (7, '7 активаций'), (8, '8 активаций'), (9, '9 активаций'), (10, '10 активаций')]),
        ),
    ]
