# Generated by Django 6.0 on 2026-01-15 19:36
# Фиктивная миграция для сервера - изменения уже применены вручную

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0026_payment_trial_reminder_sent_and_more'),
    ]

    operations = [
        # Пустая миграция - изменения уже применены в базе данных
        # Эта миграция только для того, чтобы Django знал о ней
    ]