# Generated by Django 6.0 on 2026-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0026_payment_trial_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='trial_key_expired_admin_notified',
            field=models.BooleanField(db_index=True, default=False, help_text='Было ли отправлено уведомление админу о закончившемся trial ключе (через сутки)'),
        ),
    ]
