# Generated by Django 6.0 on 2026-01-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0028_add_trial_key_expired_admin_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_just_expired_notified',
            field=models.BooleanField(db_index=True, default=False, help_text='Было ли отправлено уведомление о только что закончившейся подписке'),
        ),
    ]
