# Generated by Django 6.0 on 2026-01-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0027_add_more_activation_choices'),
        ('bot_management', '0027_add_more_activation_choices_fake'),
        ('bot_management', '0029_add_subscription_just_expired_notified'),
    ]

    operations = [
    ]
