# Generated by Django 6.0

from django.db import migrations, models


def set_current_key_expires_at_for_existing(apps, schema_editor):
    """Для существующих платежей 3м/год: current_key_expires_at = subscription_expires_at (продление не трогаем)."""
    Payment = apps.get_model('bot_management', 'Payment')
    for p in Payment.objects.filter(subscription_type__in=('3months', 'year'), current_key_expires_at__isnull=True):
        if p.subscription_expires_at:
            p.current_key_expires_at = p.subscription_expires_at
            p.save(update_fields=['current_key_expires_at'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0030_merge_server_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='current_key_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата окончания текущего месячного ключа (для 3м/год)'),
        ),
        migrations.RunPython(set_current_key_expires_at_for_existing, noop),
    ]
