# Generated by Django 6.0 on 2026-02-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0030_merge_20260117_2009'),
        ('bot_management', '0031_payment_current_key_expires_at'),
    ]

    operations = [
    ]
