# Generated by Django 6.0.1 on 2026-02-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0031_payment_current_key_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Пробная (1 день)'), ('month', 'Месячная'), ('3months', '3 месяца'), ('6months', '6 месяцев'), ('year', 'Годовая')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionkey',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Пробная (1 день)'), ('month', 'Месячная'), ('3months', '3 месяца'), ('6months', '6 месяцев'), ('year', 'Годовая')], db_index=True, max_length=10),
        ),
    ]
