# Generated by Django 6.0 on 2026-02-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0032_add_6months_subscription_type'),
        ('bot_management', '0032_merge_20260218_1614'),
    ]

    operations = [
    ]
