# Generated by Django 5.2.7 on 2026-03-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0033_merge_20260228_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vpn_type',
            field=models.CharField(choices=[('night', 'Night VPN'), ('regular', 'Обычный VPN')], db_index=True, default='night', max_length=10, verbose_name='Тип VPN'),
        ),
        migrations.AddField(
            model_name='subscriptionkey',
            name='remnawave_key_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID ключа в Remnawave'),
        ),
        migrations.AddField(
            model_name='subscriptionkey',
            name='remnawave_subscription_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID подписки в Remnawave'),
        ),
        migrations.AddField(
            model_name='subscriptionkey',
            name='remnawave_user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID пользователя в Remnawave'),
        ),
        migrations.AddField(
            model_name='subscriptionkey',
            name='vpn_type',
            field=models.CharField(choices=[('night', 'Night VPN'), ('regular', 'Обычный VPN')], db_index=True, default='night', max_length=10, verbose_name='Тип VPN'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Пробная (1 день)'), ('month', 'Месячная'), ('3months', '3 месяца'), ('6months', '6 месяцев'), ('year', 'Годовая'), ('regular_day', '1 день'), ('regular_month', '1 месяц'), ('regular_3months', '3 месяца'), ('regular_6months', '6 месяцев'), ('regular_year', '1 год'), ('regular_2years', '2 года')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionkey',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Пробная (1 день)'), ('month', 'Месячная'), ('3months', '3 месяца'), ('6months', '6 месяцев'), ('year', 'Годовая'), ('regular_day', '1 день'), ('regular_month', '1 месяц'), ('regular_3months', '3 месяца'), ('regular_6months', '6 месяцев'), ('regular_year', '1 год'), ('regular_2years', '2 года')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['vpn_type', 'status'], name='payments_vpn_typ_48c6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionkey',
            index=models.Index(fields=['vpn_type', 'is_active'], name='keys_vpn_typ_f50152_idx'),
        ),
    ]
