# Generated by Django 5.2.7 on 2026-03-18 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0034_payment_vpn_type_subscriptionkey_remnawave_key_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularVpnPayout',
            fields=[
                ('payout_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('fixed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата фиксации')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('total_payments', models.IntegerField(default=0, verbose_name='Всего платежей')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Общая сумма (₽)')),
                ('regular_day_count', models.IntegerField(default=0, verbose_name='1 день')),
                ('regular_month_count', models.IntegerField(default=0, verbose_name='1 месяц')),
                ('regular_3months_count', models.IntegerField(default=0, verbose_name='3 месяца')),
                ('regular_6months_count', models.IntegerField(default=0, verbose_name='6 месяцев')),
                ('regular_year_count', models.IntegerField(default=0, verbose_name='1 год')),
                ('regular_2years_count', models.IntegerField(default=0, verbose_name='2 года')),
                ('status', models.CharField(choices=[('pending', 'Ожидает фиксации'), ('fixed', 'Зафиксировано'), ('paid', 'Выплачено')], default='pending', max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Выплата по Обычному VPN',
                'verbose_name_plural': 'Выплаты по Обычному VPN',
                'db_table': 'regular_vpn_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='supportchat',
            options={'verbose_name': 'Чат поддержки', 'verbose_name_plural': 'Чаты поддержки'},
        ),
        migrations.RemoveIndex(
            model_name='supportchat',
            name='support_cha_user_id_b64240_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportchat',
            name='support_cha_status_e21601_idx',
        ),
    ]
