# Generated by Django 6.0.1 on 2026-03-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0035_regularvpnpayout_alter_supportchat_options_and_more'),
        ('bot_management', '0035_telegramuser_trial_key_used_night_trial_key_used_regular'),
    ]

    operations = [
    ]
