# Generated by Django 6.0.1 on 2026-04-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0036_merge_20260329_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cryptobot_asset',
            field=models.CharField(blank=True, help_text='Валюта оплаты (USDT, TON, BTC и т.д.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cryptobot_invoice_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cryptobot_payment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
