# Generated by Django 6.0.1 on 2026-04-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0037_add_cryptobot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fgcn_key_id',
            field=models.CharField(blank=True, db_index=True, help_text='Идентификатор ключа, возвращаемый API', max_length=255, null=True, verbose_name='ID ключа в FGN Connection API'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fgcn_linked_payment_ids',
            field=models.TextField(blank=True, help_text='JSON-массив ID платежей, использующих этот ключ (для мультивременных подписок)', null=True, verbose_name='Связанные платежи FGN'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fgcn_tg_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='TG ID пользователя в FGN Connection API', null=True, verbose_name='TG ID в FGN Connection API'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_fgn_key',
            field=models.BooleanField(db_index=True, default=False, help_text='True если ключ создан через новое API, False если из пула', verbose_name='Ключ создан через FGN API'),
        ),
    ]
