# Generated by Django 6.0.1 on 2026-04-11 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0038_add_fgn_connection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_renewal',
            field=models.BooleanField(db_index=True, default=False, help_text='True если это платеж за продление существующей подписки', verbose_name='Это продление'),
        ),
        migrations.AddField(
            model_name='payment',
            name='renewal_for_payment',
            field=models.ForeignKey(blank=True, help_text='Ссылка на оригинальный платеж, который продлевается', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_payments', to='bot_management.payment', verbose_name='Продление для платежа'),
        ),
    ]
