# Generated by Django 6.0 on 2026-04-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0039_add_renewal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularvpnpayout',
            name='payout_amount',
            field=models.IntegerField(default=0, help_text='Рассчитывается автоматически', verbose_name='Сумма к выплате (₽)'),
        ),
        migrations.AddField(
            model_name='regularvpnpayout',
            name='payout_percentage',
            field=models.IntegerField(default=50, help_text='Какой процент от общей суммы идёт вам', verbose_name='Процент отчислений (%)'),
        ),
    ]
