# Generated by Django 6.0 on 2026-04-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0040_regularvpnpayout_payout_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularvpnpayout',
            name='is_deducted',
            field=models.BooleanField(default=False, help_text='True если сумма уже списана с виртуального баланса', verbose_name='Списано с баланса'),
        ),
        migrations.AddField(
            model_name='regularvpnpayout',
            name='performed_by',
            field=models.BigIntegerField(blank=True, help_text='ID админа, который зафиксировал выплату', null=True, verbose_name='Выполнил (Telegram ID)'),
        ),
    ]
