# Generated by Django 6.0 on 2026-04-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0041_regularvpnpayout_is_deducted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='regular_vpn_key',
            field=models.CharField(blank=True, db_index=True, help_text='Ключ обычного VPN, выданный вместе с Night VPN', max_length=255, null=True, verbose_name='Ключ обычного VPN'),
        ),
        migrations.AddField(
            model_name='payment',
            name='regular_vpn_payment_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID связанного платежа обычного VPN', null=True, verbose_name='ID платежа обычного VPN'),
        ),
    ]
