# Generated by Django 6.0 on 2026-04-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0042_payment_regular_vpn_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='regular_vpn_remnawave_uuid',
            field=models.CharField(blank=True, db_index=True, help_text='UUID пользователя в Remnawave для продления', max_length=255, null=True, verbose_name='UUID пользователя Remnawave'),
        ),
        migrations.AddField(
            model_name='subscriptionkey',
            name='remnawave_user_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='UUID пользователя в Remnawave'),
        ),
    ]
