# Generated by Django 6.0.4 on 2026-04-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0043_payment_regular_vpn_remnawave_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bypass_remnawave_uuid',
            field=models.CharField(blank=True, db_index=True, help_text='UUID пользователя в Remnawave Bypass для продления', max_length=255, null=True, verbose_name='UUID пользователя в Bypass Remnawave'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fgcn_key_id',
            field=models.CharField(blank=True, db_index=True, help_text='Идентификатор ключа, возвращаемый API', max_length=255, null=True, verbose_name='ID ключа в API'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fgcn_linked_payment_ids',
            field=models.TextField(blank=True, help_text='JSON-массив ID платежей, использующих этот ключ', null=True, verbose_name='Связанные платежи'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fgcn_tg_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='TG ID пользователя в API', null=True, verbose_name='TG ID в API'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_fgn_key',
            field=models.BooleanField(db_index=True, default=False, help_text='True если ключ создан через API, False если из пула', verbose_name='Ключ создан через API'),
        ),
    ]
