# Generated by Django 6.0.4 on 2026-04-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0044_add_bypass_remnawave_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Пробная (1 день)'), ('month', 'Месячная'), ('3months', '3 месяца'), ('6months', '6 месяцев'), ('year', 'Годовая'), ('regular_day', '1 день (ULTRA FAST)'), ('regular_month', '1 месяц (ULTRA FAST)'), ('regular_3months', '3 месяца (ULTRA FAST)'), ('regular_6months', '6 месяцев (ULTRA FAST)'), ('regular_year', '1 год (ULTRA FAST)'), ('regular_2years', '2 года (ULTRA FAST)'), ('fast_day', '1 день (Fast VPN)'), ('fast_month', '1 месяц (Fast VPN)'), ('fast_3months', '3 месяца (Fast VPN)'), ('fast_6months', '6 месяцев (Fast VPN)'), ('fast_year', '1 год (Fast VPN)')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vpn_type',
            field=models.CharField(choices=[('night', 'ОБХОД глушилок + VPN'), ('regular', 'Обычный VPN'), ('fast', 'Fast VPN')], db_index=True, default='night', max_length=10, verbose_name='Тип VPN'),
        ),
        migrations.AlterField(
            model_name='subscriptionkey',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Пробная (1 день)'), ('month', 'Месячная'), ('3months', '3 месяца'), ('6months', '6 месяцев'), ('year', 'Годовая'), ('regular_day', '1 день (ULTRA FAST)'), ('regular_month', '1 месяц (ULTRA FAST)'), ('regular_3months', '3 месяца (ULTRA FAST)'), ('regular_6months', '6 месяцев (ULTRA FAST)'), ('regular_year', '1 год (ULTRA FAST)'), ('regular_2years', '2 года (ULTRA FAST)'), ('fast_day', '1 день (Fast VPN)'), ('fast_month', '1 месяц (Fast VPN)'), ('fast_3months', '3 месяца (Fast VPN)'), ('fast_6months', '6 месяцев (Fast VPN)'), ('fast_year', '1 год (Fast VPN)')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionkey',
            name='vpn_type',
            field=models.CharField(choices=[('night', 'ОБХОД глушилок + VPN'), ('regular', 'Обычный VPN'), ('fast', 'Fast VPN')], db_index=True, default='night', max_length=10, verbose_name='Тип VPN'),
        ),
    ]
