# Generated by Django 6.0.4 on 2026-04-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0045_add_fast_vpn_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='profit',
            field=models.IntegerField(default=0, verbose_name='Чистая прибыль'),
        ),
    ]
