# Generated by Django 6.0.4 on 2026-04-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0046_add_payment_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='trial_key_used_fast',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Использован пробный ключ Fast VPN'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='trial_key_used_regular',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Использован пробный ключ Обычный VPN'),
        ),
    ]
