# Generated by Django 6.0.4 on 2026-04-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0047_add_trial_key_used_fast'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='ban_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Причина бана'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_banned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Забанен'),
        ),
    ]
