# Generated by Django 6.0.4 on 2026-07-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0050_add_hourly_reminder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='antilopay_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='antilopay_payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription_reminder_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Было ли отправлено напоминание о заканчивающейся подписке (3 дня)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Пробная (3 дня)'), ('month', 'Месячная'), ('3months', '3 месяца'), ('6months', '6 месяцев'), ('year', 'Годовая'), ('regular_day', '1 день (ULTRA FAST)'), ('regular_month', '1 месяц (ULTRA FAST)'), ('regular_3months', '3 месяца (ULTRA FAST)'), ('regular_6months', '6 месяцев (ULTRA FAST)'), ('regular_year', '1 год (ULTRA FAST)'), ('regular_2years', '2 года (ULTRA FAST)'), ('fast_day', '1 день (Обычный VPN)'), ('fast_month', '1 месяц (Обычный VPN)'), ('fast_3months', '3 месяца (Обычный VPN)'), ('fast_6months', '6 месяцев (Обычный VPN)'), ('fast_year', '1 год (Обычный VPN)')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionkey',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Пробная (3 дня)'), ('month', 'Месячная'), ('3months', '3 месяца'), ('6months', '6 месяцев'), ('year', 'Годовая'), ('regular_day', '1 день (ULTRA FAST)'), ('regular_month', '1 месяц (ULTRA FAST)'), ('regular_3months', '3 месяца (ULTRA FAST)'), ('regular_6months', '6 месяцев (ULTRA FAST)'), ('regular_year', '1 год (ULTRA FAST)'), ('regular_2years', '2 года (ULTRA FAST)'), ('fast_day', '1 день (Обычный VPN)'), ('fast_month', '1 месяц (Обычный VPN)'), ('fast_3months', '3 месяца (Обычный VPN)'), ('fast_6months', '6 месяцев (Обычный VPN)'), ('fast_year', '1 год (Обычный VPN)')], db_index=True, max_length=20),
        ),
    ]
