# Generated by Django 6.0 on 2026-07-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0051_payment_antilopay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='vpn_type',
            field=models.CharField(choices=[('night', 'ускоритель интернета + VPN'), ('regular', '⚡ ULTRA FAST VPN'), ('fast', 'Обычный VPN')], db_index=True, default='night', max_length=10, verbose_name='Тип VPN'),
        ),
        migrations.AlterField(
            model_name='subscriptionkey',
            name='vpn_type',
            field=models.CharField(choices=[('night', 'ускоритель интернета + VPN'), ('regular', '⚡ ULTRA FAST VPN'), ('fast', 'Обычный VPN')], db_index=True, default='night', max_length=10, verbose_name='Тип VPN'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='trial_key_used_fast',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Использован пробный ключ Обычный VPN'),
        ),
    ]
