# Generated by Django 6.0.4 on 2026-07-06 21:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0053_payment_antilopay_recurrent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Код')),
                ('discount_percent', models.IntegerField(verbose_name='Скидка (%)')),
                ('max_uses', models.IntegerField(default=0, verbose_name='Макс. использований (0 = безлимит)')),
                ('current_uses', models.IntegerField(default=0, verbose_name='Текущее использований')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'db_table': 'promo_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма до скидки'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vpn_type',
            field=models.CharField(choices=[('night', 'ОБХОД глушилок + VPN'), ('regular', '⚡ ULTRA FAST VPN'), ('fast', 'Обычный VPN')], db_index=True, default='night', max_length=10, verbose_name='Тип VPN'),
        ),
        migrations.AlterField(
            model_name='subscriptionkey',
            name='vpn_type',
            field=models.CharField(choices=[('night', 'ОБХОД глушилок + VPN'), ('regular', '⚡ ULTRA FAST VPN'), ('fast', 'Обычный VPN')], db_index=True, default='night', max_length=10, verbose_name='Тип VPN'),
        ),
        migrations.AddField(
            model_name='payment',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_management.promocode', verbose_name='Промокод'),
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Использован')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_usages', to='bot_management.payment')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='bot_management.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to='bot_management.telegramuser')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
                'db_table': 'promo_code_usages',
                'unique_together': {('promo_code', 'user')},
            },
        ),
    ]
