# Generated by Django 6.1 on 2026-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0056_add_antilopay_order_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promocodeusage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payment',
            name='switched_to_expired_squad',
            field=models.BooleanField(db_index=True, default=False, help_text='Переключен ли пользователь на сквад истёкшей подписки (22a6415e-db7b-486c-8c8a-ccecf42d8459)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Пробная (3 дня)'), ('regular_trial', 'Пробная ULTRA FAST (3 дня)'), ('fast_trial', 'Пробная Обычный VPN (3 дня)'), ('month', 'Месячная'), ('3months', '3 месяца'), ('6months', '6 месяцев'), ('year', 'Годовая'), ('regular_day', '1 день (ULTRA FAST)'), ('regular_month', '1 месяц (ULTRA FAST)'), ('regular_3months', '3 месяца (ULTRA FAST)'), ('regular_6months', '6 месяцев (ULTRA FAST)'), ('regular_year', '1 год (ULTRA FAST)'), ('regular_2years', '2 года (ULTRA FAST)'), ('fast_day', '1 день (Обычный VPN)'), ('fast_month', '1 месяц (Обычный VPN)'), ('fast_3months', '3 месяца (Обычный VPN)'), ('fast_6months', '6 месяцев (Обычный VPN)'), ('fast_year', '1 год (Обычный VPN)')], db_index=True, max_length=20),
        ),
    ]
